---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: docker.io/webdevops/ssh
    # privileged: True
    # volumes:
    #   - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    # command: "/usr/bin/init"
    # tty: True
    # pre_build_image: True
    exposed_ports:
      - 22/tcp
      - 11260/tcp
    published_ports:
      - 0.0.0.0:22:22/tcp
      - 0.0.0.0:11260:11260/tcp
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  lint:
    name: ansible-lint
    enabled: true
verifier:
  name: testinfra
  lint:
    name: flake8
